FROM quay.io/almalinuxorg/almalinux-bootc:9.4


RUN dnf install -y epel-release && dnf config-manager --set-enabled crb

RUN dnf install -y --nobest \
	--excludepkgs rootfiles,firefox,totem,Packagekit,gnome-tour,gnome-initial-setup,alsa-sof-firmware \
	@Workstation && rm -rdf /var/run

RUN dnf remove -y evolution plymouth setroubleshoot cockpit

RUN wget -O /usr/lib/firewalld/zones/HeliumOS.xml \
	https://src.fedoraproject.org/rpms/firewalld/raw/90e646ef020a9c2e680a3f7c296e8ce1d4a5abc5/f/FedoraWorkstation.xml \
	&& sed -i 's,DefaultZone=public,DefaultZone=HeliumOS,g' /etc/firewalld/firewalld.conf

RUN dnf install -y \
	gnome-tweaks gnome-extensions-app \
	gnome-shell-extension-appindicator \
	NetworkManager-openvpn-gnome

RUN dnf install -y https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/35/Everything/x86_64/os/Packages/g/gnome-shell-extension-gsconnect-47-2.fc35.x86_64.rpm

RUN dnf install -y distrobox chromium git firewall-config

RUN sed -i 's,wiki.almalinux.org,heliumos.org/docs,g' /usr/lib/os-release && \
    sed -i 's,LOGO="fedora-logo-icon",LOGO="heliumos-logo-icon",g' /usr/lib/os-release && \
    sed -i 's,ID="almalinux",ID="heliumos",g' /usr/lib/os-release && \
    sed -i 's,ALMALINUX_MANTISBT_PROJECT="AlmaLinux-9",,g' /usr/lib/os-release && \
    sed -i 's,ALMALINUX_MANTISBT_PROJECT_VERSION="9.4",,g' /usr/lib/os-release && \
    sed -i 's,Seafoam Ocelot,Fire Cypress,g' /usr/lib/os-release && \
    sed -i 's,AlmaLinux,HeliumOS,g' /usr/lib/os-release && \
    sed -i 's,almalinux,heliumos,g' /usr/lib/os-release && \
    sed -i 's,ID_LIKE="rhel centos fedora",ID_LIKE="rhel centos fedora almalinux",g' /usr/lib/os-release

RUN git clone https://codeberg.org/HeliumOS/logo.git && \
	cd logo && \
	git checkout 0ce8b5cd8f && \
	mv export/logo/logo-color.svg /usr/share/icons/hicolor/scalable/apps/heliumos-logo-icon.svg && \
	mv export/logo/logo.svg /usr/share/icons/hicolor/scalable/apps/heliumos-logo-icon-white.svg && \
	mv export/logo/logo-color-256x256.png /usr/share/icons/hicolor/256x256/apps/heliumos-logo-icon.png && \
	mv export/logo/logo-color-64x64.png /usr/share/icons/hicolor/64x64/apps/heliumos-logo-icon.png && \
	ln -sf /usr/share/icons/hicolor/scalable/apps/heliumos-logo-icon.svg /usr/share/icons/hicolor/scalable/apps/start-here.svg && \
	ln -sf /usr/share/icons/hicolor/scalable/apps/heliumos-logo-icon.svg /usr/share/icons/hicolor/scalable/apps/xfce4_xicon1.svg && \
	ln -sf /usr/share/icons/hicolor/scalable/apps/heliumos-logo-icon.svg /usr/share/almalinux-logos/fedora_logo.svg && \
	ln -sf /usr/share/icons/hicolor/scalable/apps/heliumos-logo-icon-white.svg /usr/share/almalinux-logos/fedora_logo_darkbackground.svg && \
	ln -sf /usr/share/icons/hicolor/scalable/apps/heliumos-logo-icon.svg /usr/share/pixmaps/fedora-logo-sprite.svg && \
	ln -sf /usr/share/icons/hicolor/256x256/apps/heliumos-logo-icon.png /usr/share/pixmaps/fedora-logo-sprite.png && \
	ln -sf /usr/share/icons/hicolor/256x256/apps/heliumos-logo-icon.png /usr/share/pixmaps/fedora-logo.png && \
	ln -sf /usr/share/icons/hicolor/64x64/apps/heliumos-logo-icon.png /usr/share/pixmaps/fedora-gdm-logo.png && \
	ln -sf /usr/share/icons/hicolor/64x64/apps/heliumos-logo-icon.png /usr/share/pixmaps/fedora-logo-small.png && \
	cd .. && rm -rdf logo

RUN git clone https://codeberg.org/HeliumOS/wallpapers.git --depth=1 && \
	cd wallpapers && \
	mv desktop-backgrounds-default.xml /usr/share/gnome-background-properties/desktop-backgrounds-default.xml && \
	mkdir -p /usr/share/backgrounds/heliumos && \
	cp ./*.jpg /usr/share/backgrounds/heliumos && \
	cd .. && rm -rdf wallpapers

COPY gschema_overrides/* /usr/share/glib-2.0/schemas/

RUN glib-compile-schemas /usr/share/glib-2.0/schemas/

COPY ./*.service /usr/lib/systemd/system/

RUN sed -i 's,ExecStart=/usr/bin/bootc update --apply --quiet,ExecStart=/usr/bin/bootc update --quiet,g' /usr/lib/systemd/system/bootc-fetch-apply-updates.service
