- name: Add Fedora repo
  ansible.builtin.copy:
    content: |
      [fedora]
      name=Fedora {{ fedora_releasever }} - $basearch - Updates
      #baseurl=http://download.example/pub/fedora/linux/updates/{{ fedora_releasever }}/Everything/$basearch/
      metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-f{{ fedora_releasever }}&arch=$basearch
      enabled=0
      countme=1
      repo_gpgcheck=0
      type=rpm
      gpgcheck=1
      metadata_expire=6h
      gpgkey=https://src.fedoraproject.org/rpms/fedora-repos/raw/rawhide/f/RPM-GPG-KEY-fedora-{{ fedora_releasever }}-primary
      skip_if_unavailable=False
    dest: /etc/yum.repos.d/fedora.repo
  vars:
    fedora_releasever: 42

- name: Install Fedora kernel
  ansible.builtin.dnf:
    enablerepo: fedora
    disablerepo: baseos,appstream
    name:
      - kernel
      - kernel-devel
      - kernel-headers
    state: latest
