- name: CentOS Hyperscale Kernel dnf repository
  ansible.builtin.copy:
    content: |
      [centos-hyperscale-kernel]
      name=CentOS Stream $releasever - Hyperscale Kernel
      #metalink=https://mirrors.centos.org/metalink?repo=centos-hyperscale-sig-packages-kernel-$stream&arch=$basearch&protocol=https,http
      baseurl=https://mirror.stream.centos.org/SIGs/10-stream/hyperscale/$basearch/packages-kernel/
      gpgcheck=1
      enabled=1
      countme=1
      priority=50
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-HyperScale
    dest: /etc/yum.repos.d/centos-hyperscale-kernel.repo

- name: CentOS Hyperscale dnf repository GPG Key
  ansible.builtin.get_url:
    url: https://gitlab.com/CentOS/Hyperscale/rpms/centos-release-hyperscale/-/raw/89c9e6f1b585090756d4dd9e07f79a935e5dbafb/RPM-GPG-KEY-CentOS-SIG-HyperScale
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-HyperScale

- name: Install CentOS Hyperscale Kernel
  ansible.builtin.dnf:
    name: kernel
    state: latest

- name: Remove stock kernel
  shell:
    cmd: |
      current_kernel=$(dnf list installed kernel | awk '/kernel/{print $2}' | head -n1)
      find /lib/modules /usr/lib/modules -mindepth 1 -maxdepth 1 -type d \
      ! -name "$current_kernel*" -exec rm -rf {} +
