# - name: Install NVIDIA dnf repository
#   ansible.builtin.copy:
#     content: |
#       [cuda-fedora42-x86_64]
#       name=cuda-fedora42-x86_64
#       baseurl=https://developer.download.nvidia.com/compute/cuda/repos/fedora42/x86_64
#       enabled=1
#       gpgcheck=0
#     dest: /etc/yum.repos.d/nvidia-fedora.repo

- name: Install NVIDIA dnf repository
  ansible.builtin.copy:
    content: |
      [fedora-nvidia-580]
      name=negativo17 - Nvidia
      baseurl=https://negativo17.org/repos/nvidia-580/fedora-{{ fedora_releasever }}/$basearch/
      enabled=1
      skip_if_unavailable=1
      gpgcheck=1
      gpgkey=https://negativo17.org/repos/RPM-GPG-KEY-slaanesh
      enabled_metadata=1
      metadata_expire=6h
      type=rpm-md
      repo_gpgcheck=0
    dest: /etc/yum.repos.d/nvidia-fedora.repo
  vars:
    fedora_releasever: 42

- name: Install NVIDIA kmod drivers
  ansible.builtin.dnf:
    enablerepo: fedora
    name:
      - nvidia-driver
      - dkms-nvidia
    state: present

- name: Configure SDDM theme
  shell:
    cmd: |
      sed -i -e 's/kernel$/kernel-open/g' /etc/nvidia/kernel.conf
      dkms build -m nvidia/580.119.02 --force
      dkms install -m nvidia/580.119.02 --force
