- name: Install NVIDIA dnf repository
  ansible.builtin.copy:
    content: |
      [cuda-fedora42-x86_64]
      name=cuda-fedora42-x86_64
      baseurl=https://developer.download.nvidia.com/compute/cuda/repos/fedora42/x86_64
      enabled=1
      gpgcheck=0
    dest: /etc/yum.repos.d/nvidia-fedora.repo

- name: Install NVIDIA kmod drivers
  ansible.builtin.dnf:
    name:
      - nvidia-open
      - nvidia-driver
      - kmod-nvidia-open-dkms
    state: present
