- name: Install NVIDIA dnf repository
  ansible.builtin.copy:
    content: |
      [fedora-nvidia]
      name=negativo17 - Nvidia
      baseurl=https://negativo17.org/repos/nvidia/fedora-{{ fedora_releasever }}/$basearch/
      enabled=1
      skip_if_unavailable=1
      gpgcheck=1
      gpgkey=https://negativo17.org/repos/RPM-GPG-KEY-slaanesh
      enabled_metadata=1
      metadata_expire=6h
      type=rpm-md
      repo_gpgcheck=0
    dest: /etc/yum.repos.d/nvidia-fedora.repo
  vars:
    fedora_releasever: 43

- name: Install NVIDIA kmod drivers
  ansible.builtin.dnf:
    name:
      - kmod-nvidia
      - nvidia-driver
      - nvidia-settings
    state: present
