# - name: Install NVIDIA dnf repository (negativo)
#   shell:
#     cmd: |
#       dnf config-manager \
#         --add-repo=https://negativo17.org/repos/epel-nvidia.repo

# - name: Install NVIDIA dkms driver sources
#   ansible.builtin.dnf:
#     name:
#       - nvidia-driver
#       - dkms-nvidia
#     state: present

- name: Install NVIDIA dnf repository
  shell:
    cmd: |
      dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel10/x86_64/cuda-rhel10.repo

- name: Install NVIDIA dkms drivers
  ansible.builtin.dnf:
    name:
      - nvidia-driver
      - kmod-nvidia-open-dkms
    state: present
# - name: Build and install NVIDIA dkms drivers
#   shell:
#     cmd: |
#       nvidia_version=$(dnf list installed | grep dkms | grep nvidia | awk '{print $2}' | cut -d':' -f2- | cut -d'-' -f1)
#       kernel_version=$(dnf list installed kernel | awk '/kernel/{print $2}' | head -n1).x86_64
#       dkms build -m nvidia/${nvidia_version} -k ${kernel_version} --force
#       dkms install -m nvidia/${nvidia_version} -k ${kernel_version} --force

# - name: Download NVIDIA .run installer
#   ansible.builtin.get_url:
#     url: https://in.download.nvidia.com/XFree86/Linux-x86_64/580.119.02/NVIDIA-Linux-x86_64-580.119.02.run
#     dest: /NVIDIA.run
#     mode: "0755"
#     checksum: sha256:8020f5dfd3ee88aee7a38990d0c3d2afe54751e9a170ba9eadd7ea670138ecd7

# - name: Build and install NVIDIA dkms drivers
#   shell:
#     cmd: |
#       nvidia_version=$(dnf list installed | grep dkms | grep nvidia | awk '{print $2}' | cut -d':' -f2- | cut -d'-' -f1)
#       kernel_version=$(dnf list installed kernel | awk '/kernel/{print $2}' | head -n1).x86_64
#       /NVIDIA.run -M open --disable-nouveau --silent --kernel-source-path=/lib/modules/${kernel_version}/build
#       rm /NVIDIA.run
