- name: Install NVIDIA dnf repository
  ansible.builtin.dnf:
    name:
      - almalinux-release-nvidia-driver
    state: present

- name: Use major-stable NVIDIA dnf repository
  shell:
    cmd: |
      sed -i \
        's,rhel$releasever,rhel10,g' \
        /etc/yum.repos.d/nvidia-cuda.repo

- name: Install NVIDIA kmod drivers
  ansible.builtin.dnf:
    name:
      - nvidia-open
    state: present
