- name: Patch Bootc update service to remove apply
  ansible.builtin.replace:
    path: /usr/lib/systemd/system/bootc-fetch-apply-updates.service
    regexp: "bootc upgrade --apply"
    replace: "bootc upgrade"

- name: Set /opt mutable
  shell:
    cmd: |
      mv /opt /var/opt
      ln -s /var/opt /opt

- name: Reboot on Kernel Panic
  ansible.builtin.copy:
    content: |
      kargs = ["panic=3"]
    dest: /usr/lib/bootc/kargs.d/10-kernel-panic-reboot.toml

- name: Disable rpm-ostree-countme service
  ansible.builtin.file:
    path: /etc/systemd/system/timers.target.wants/rpm-ostree-countme.timer
    state: absent
