- name: Install Development Tools
  ansible.builtin.dnf:
    name:
      - "@development"
      - distrobox
    state: present

- name: Install Development Libraries
  ansible.builtin.dnf:
    name:
      - gmp-devel
    state: present
