name: Build and Push image

on:
  workflow_call:
    inputs:
      version:
        description: "The EL version: 9, (10 soon), etc."
        required: true
        type: string
      is_canary:
        description: "Whether this is a canary release"
        required: true
        type: boolean
      variant:
        description: "The system variant: \"\", edge, etc."
        required: true
        type: boolean

jobs:
   name: Build and Push image
   runs-on: ubuntu-24.04
   steps:

     - name: Checkout repository
       uses: actions/checkout@v4

     - name: Install build dependencies
       run: |
         apt-get install -y podman

     - name: Build image
       env:
         VERSION: ${{ inputs.version }}
         VARIANT: ${{ inputs.variant }}
       run: |
         if [[ $VARIANT == "" ]]; then
           export CONTAINERFILE=$VERSION/Containerfile
         else
           export CONTAINERFILE=$VERSION/Containerfile.$VARIANT
         fi 
         podman build -t localhost/heliumos-bootc -f $CONTAINERFILE .

     - name: Login to registry
       env:
         REGISTRY_USER: ${{ secrets.registry_user }}
         REGISTRY_PASS: ${{ secrets.registry_pass }}
         REGISTRY_URI: ${{ secrets.registry_uri }}
       run: |
         podman login --username $REGISTRY_USER --password $REGISTRY_PASS $REGISTRY_URI

     - name: Push to registry
       env:
         REGISTRY_URI: ${{ secrets.registry_uri }}
         VERSION: ${{ inputs.version }}
         VARIANT: ${{ inputs.variant }}
       run: |
         if [[ $IS_CANARY ]]; then
           export VERSION=$VERSION-canary
         fi

         if [[ $VARIANT == "" ]]; then
           export TAG=$VERSION
         else
           export TAG=$VERSION-$VARIANT
         fi
         podman push localhost/heliumos-bootc $REGISTRY_URI:$TAG
 
