name: HeliumOS Canary Release
on:
  push:
    branches:
      - release
      - gha

jobs:
  build_and_push:
    uses: ./.github/workflows/build-and-push.yaml
    secrets: inherit
    strategy:
      matrix:
        version: [9]
        variant: ["", "edge"]
    with:
      version: ${{ matrix.version }}
      is_canary: true
      variant: ${{ matrix.variant }}

