name: HeliumOS Canary Release
on:
  push:
    branches:
      - release
      - gha

jobs:
  build_and_push:
    uses: ./.github/workflows/build-and-push.yaml
    secrets: inherit
    with:
      is_canary: true

