name: HeliumOS Stable Release
on:
  push:
    branches:
      - release

jobs:
  build_and_push:
    uses: ./.github/workflows/build-and-push.yaml
    secrets: inherit
    with:
      is_canary: false

